[env:genericSTM32H750VB]
platform = ststm32@19.7.0
board = genericSTM32H750VB
framework = arduino
platform_packages =
    tool-openocd@~2.1100.0
lib_extra_dirs =
    ../../AccelStepper-master
    ../../lib
upload_protocol = cmsis-dap
debug_tool = cmsis-dap
monitor_port = COM10
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 1
